version: "3"

services:

  ckan-ed:
    container_name: ckan-ed
    build:
      context: ckan/
      dockerfile: Dockerfile.dev.ed
    env_file:
      - .env.ed      
    links:
      - db-ed
      - solr-ed
      - redis-ed
        #- datapusher-ed
    networks:
      default:
        aliases:
          - ckan
    ports:
      - "5000:5000"
    volumes:
      - ckan_storage_ed:/var/lib/ckan-ed
      - ./src:/srv/app/src_extensions
      # debug extensions
      - /home/leo/Freelancing/Datopian/us-dept-of-education/ckanext-ed:/srv/app/src_extensions/ckanext-ed
      #- /home/higor/Documents/Datopian/Projects/extensions/ckanext-collections:/srv/app/src_extensions/ckanext-collections
      #- /home/higor/Documents/Datopian/Projects/extensions/ckanext-harvest:/srv/app/src_extensions/ckanext-harvest
      #- /home/higor/Documents/Datopian/Projects/extensions/ckanext-datajson:/srv/app/src_extensions/ckanext-datajson

        #  datapusher-ed:
        #    container_name: datapusher-ed
        #    image: keitaro/ckan-datapusher:0.0.17
        #    ports:
        #        - "8000:8000"
        #    environment:
        #        - DATAPUSHER_SSL_VERIFY=False
        #        - DATAPUSHER_REWRITE_URL=http://ckan:5000/
        #        - DATAPUSHER_MAX_CONTENT_LENGTH=80000000

  db-ed:
    container_name: db-ed
    env_file:
      - .env.ed
    build:
      context: postgresql/
    volumes:
      - pg_data_ed:/var/lib/postgresql/data

  solr-ed:
    container_name: solr-ed
    build:
      context: solr/
    volumes:
      - solr_data_ed:/opt/solr/server/solr/ckan/data/index

  redis-ed:
    container_name: redis-ed
    image: redis:alpine

volumes:
  ckan_storage_ed:
  pg_data_ed:
  solr_data_ed:
