FROM alpine:3.8
ENV TZ UTC

# Set CKAN version to build
ENV GIT_URL=https://github.com/ckan/ckan.git
ENV GIT_BRANCH=ckan-2.9

# Set src dirs
ENV SRC_DIR=/srv/app/src
ENV PIP_SRC=${SRC_DIR}
ENV APP_DIR=/srv/app
ENV SRC_EXTENSIONS_DIR=/srv/app/src_extensions

ENV CKAN_STORAGE_PATH=$CKAN_STORAGE_PATH

ENV CKAN__SITE_URL=http://ckan:5000
ENV CKAN__PLUGINS envvars image_view text_view recline_view datastore datapusher
ENV CKAN_INI=/srv/app/development.ini

WORKDIR ${SRC_DIR}

# Packages to build CKAN requirements and plugins
RUN apk add --no-cache tzdata \
                        git \
                        gettext \
                        postgresql-client \
                        python2 \
                        apache2-utils \
                        libxml2 \
                        libxslt \
                        musl-dev \
                        py2-gevent \
                        uwsgi \
                        uwsgi-http \
                        uwsgi-corerouter \
                        uwsgi-python \
                        uwsgi-gevent \
                        libmagic \
                        curl 

RUN apk add --no-cache --virtual .build-deps \
                                    postgresql-dev  \
                                    gcc \
                                    make \
                                    g++ \
                                    autoconf \
                                    automake \
                                    libtool \
                                    python-dev \
                                    libxml2-dev \
                                    libxslt-dev \
                                    linux-headers 

RUN apk add --no-cache libffi-dev
                                
RUN mkdir -p ${SRC_DIR} 

RUN curl -o ${SRC_DIR}/get-pip.py https://bootstrap.pypa.io/2.7/get-pip.py && \
    python ${SRC_DIR}/get-pip.py pip==20.3.3 wheel==0.36.2 setuptools==44.1.1 && \
    pip install supervisor

RUN rm -rf ${SRC_DIR}/get-pip.py

RUN pip install -e git+${GIT_URL}@${GIT_BRANCH}#egg=ckan
RUN cd ${SRC_DIR}/ckan && cp who.ini ${APP_DIR}
RUN cd ${SRC_DIR}/ckan && pip install --no-binary :all: -r requirements.txt 

RUN pip install -e git+https://github.com/okfn/ckanext-envvars.git#egg=ckanext-envvars
RUN pip install -e git+https://github.com/ckan/ckanext-googleanalytics#egg=ckanext-googleanalytics
RUN pip install -r https://raw.githubusercontent.com/ckan/ckanext-googleanalytics/master/requirements.txt

RUN paster --plugin=ckan make-config ckan ${CKAN_INI}

# Create a local user and group to run the app
RUN addgroup -g 92 -S ckan && \
    adduser -u 92 -h /srv/app -H -D -S -G ckan ckan

#RUN mkdir -p ${CKAN_STORAGE_PATH}
#RUN chown -R ckan:ckan ${CKAN_STORAGE_PATH}

ONBUILD RUN mkdir /docker-entrypoint.d
#COPY docker-entrypoint.d/vanilla/* /docker-entrypoint.d/

COPY setup/uwsgi.conf /srv/app
COPY setup/prerun.py /srv/app

RUN mkdir /etc/supervisord.d
RUN mkdir /tmp/supervisord
RUN chown -R ckan.ckan /tmp/supervisord
RUN chown -R ckan.ckan /etc/supervisord.d

COPY setup/supervisord.conf /etc
COPY setup/supervisord.d/* /etc/supervisord.d/

COPY setup/google-analytics/ckan-local-google-credentials.json ${APP_DIR}

RUN chown -R ckan.ckan ${APP_DIR}

EXPOSE 5000

CMD ["/srv/app/start_ckan.sh"]

RUN pip install --no-binary :all: -r https://raw.githubusercontent.com/ckan/ckan/${GIT_BRANCH}/dev-requirements.txt

COPY setup/start_ckan_development.sh /srv/app

RUN mkdir $SRC_EXTENSIONS_DIR
RUN chown -R ckan.ckan ${SRC_EXTENSIONS_DIR}

CMD ["/srv/app/start_ckan_development.sh"]